bot:
  token: null
  pet-species:
    - cat
    - dog
    - parrot
    - hamster
    - snake
    - dragon
    - fox
    - deer
    - squirrel
    - beast
  training-cooldown-in-seconds: 720
  status-background: null
  status-color: null
  training-channels: 0

database:
  host: "localhost:3306"
  name: "database"
  user: "user"
  password: "password"

#internals
spring:
  datasource:
    hikari:
      username: "${database.user}"
      password: "${database.password}"
      driver-class-name: "com.mysql.cj.jdbc.Driver"
      auto-commit: true
      connection-test-query: select 1
      maximum-pool-size: 20
    url: "jdbc:mysql://${database.host}/${database.name}"
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true